### ISSUE TITLE
Theming Support

### ISSUE THREAD

**Issue by minecrawler** [Skellods-Network/SHPS4Node-CSS#6]
Support for themes according to Harry Roberts'  BEMIT.

For example

```html
<!DOCTYPE HTML>
<html>
<body class="t-light">
  <div class="c-content"></div>
  <footer class="c-footer"></footer>
```

```css
.t-light .c-content {
  background-color: hsl(0, 0%, 98%);
  color: hsl(0, 0%, 5%);
}

.t-light .c-footer {
  background-color: hsl(0, 20%, 80%);
  color: hsl(0, 0%, 2%);
}

.t-dark .c-content {
  background-color: hsl(0, 0%, 15%);
  color: hsl(0, 0%, 95%);
}

.t-dark .c-footer {
  background-color: hsl(0, 20%, 20%);
  color: hsl(0, 0%, 98%);
}
```

As you can see, for this kind of theming to work (one exchangable class), all classes which contain style information directly linked to theming have to be a subclass of the theme class. SHPS could help developers with this kind of thing by linking all theme-related CSS to a theme. That would also make it very easy to add new themes as one could just copy all CSS rules in a theme and then style them instead of searching for them in hacky ways.
